### ISSUE TITLE
Bucket name already taken on GCS global namespace

### ISSUE THREAD

**Issue by jonathonHill123** [datherra/sponsoroo-letsencrypt#1]
Suggested fix: update BUCKET_NAME in issue.sh from tw-certs to tw-certs-sponsoroo

**Comment by datherra** [comment]
Hi @jcgh582 , I invited you as collaborator instead.
Could you please retry the fix and push?

Cheers

**Comment by jonathonHill123** [comment]
I pushed the suggested fix; commitId: 6e378c3e304fdce7fb5a859312f9c53bd1de489b.
We can close this issue :).
